import { inter } from './ui/fonts';

import type { Metadata } from 'next';

// fonts
import { Toaster } from '@/components/ui/toaster';
import SessionProvider from '@/context/SessionProvider';

import './globals.css';

// ----------------------------------------------------------------

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IRootLayout {
  readonly children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayout> = async ({ children }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <SessionProvider>
          {children}
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
