import type { Metadata } from 'next';

import '../globals.css';

// ----------------------------------------------------------------

interface ILayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<ILayoutProps> = ({ children }) => {
  return (
    <section className="flex h-screen">
      <div className="flex flex-1 flex-col">{children}</div>
    </section>
  );
};

export default RootLayout;
